package com.grana.user.domain.model.user;

import java.sql.Timestamp;
import java.util.List;

import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;

/**
 * 用户信息数据模型
 * 聚合根
 * 
 *
 * @author Aaron Ma
 * @Date 2020-9-22 13:35:6
 */
public class User implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5232249421475896614L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /** 用户帐号 */
    private String userCode;

    /** 用户昵称 */
    private String nickName;

    /** 性别 */
    private Integer sex;

    /** 头像地址 */
    private String avatar;

    /** 帐号状态：0->禁用；1->启用 */
    private Integer status;

    /** createdBy */
    private String createdBy;

    /** createdTime */
    @TableField(fill = FieldFill.INSERT)
    private Timestamp createdTime;

    /** modifiedBy */
    private String modifiedBy;

    /** modifiedTime */
    @TableField(fill = FieldFill.UPDATE)
    private Timestamp modifiedTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取用户帐号
     * 
     * @return 用户帐号
     */
    public String getUserCode() {
        return this.userCode;
    }

    /**
     * 设置用户帐号
     * 
     * @param userCode
     *          用户帐号
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * 获取用户昵称
     * 
     * @return 用户昵称
     */
    public String getNickName() {
        return this.nickName;
    }

    /**
     * 设置用户昵称
     * 
     * @param nickName
     *          用户昵称
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * 获取性别
     * 
     * @return 性别
     */
    public Integer getSex() {
        return this.sex;
    }

    /**
     * 设置性别
     * 
     * @param sex
     *          性别
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * 获取头像地址
     * 
     * @return 头像地址
     */
    public String getAvatar() {
        return this.avatar;
    }

    /**
     * 设置头像地址
     * 
     * @param avatar
     *          头像地址
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * 获取帐号状态：0->禁用；1->启用
     * 
     * @return 帐号状态
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * 设置帐号状态：0->禁用；1->启用
     * 
     * @param status
     *          帐号状态
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 获取createdBy
     * 
     * @return createdBy
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * 设置createdBy
     * 
     * @param createdBy
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * 获取createdTime
     * 
     * @return createdTime
     */
    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    /**
     * 设置createdTime
     * 
     * @param createdTime
     */
    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 获取modifiedBy
     * 
     * @return modifiedBy
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * 设置modifiedBy
     * 
     * @param modifiedBy
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * 获取modifiedTime
     * 
     * @return modifiedTime
     */
    public Timestamp getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * 设置modifiedTime
     * 
     * @param modifiedTime
     */
    public void setModifiedTime(Timestamp modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
    
    /** 用户凭证信息 */
    @TableField(exist = false)
    private List<UserAuth> userAuths;

    public List<UserAuth> getUserAuths() {
        return userAuths;
    }

    public void setUserAuths(List<UserAuth> userAuths) {
        this.userAuths = userAuths;
    }
    
    
}