package com.grana.user.domain.model.user;

import java.sql.Timestamp;
import java.util.Date;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.grana.user.domain.shared.ValueObject;

/**
 * 用户凭证信息
 * 表：user_auth
 *
 * @author Aaron Ma
 * @Date 2021-3-1 15:26:29
 */
public class UserAuth implements ValueObject<UserAuth> {
    /** 版本号 */
    private static final long serialVersionUID = 682253526510875358L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    /** userId */
    private Long userId;

    /** 登录类型(手机/邮箱/QQ/微信...) */
    private IdentityType identityType;

    /** 登录唯一标识 */
    private String identifier;

    /** 登录凭证 */
    private String credentials;

    /** 最后登录IP */
    private String loginIp;

    /** 最后登录时间 */
    private Date loginTime;

    /** createdBy */
    private String createdBy;

    /** createdTime */
    private Timestamp createdTime;

    /** modifiedBy */
    private String modifiedBy;

    /** modifiedTime */
    private Timestamp modifiedTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取userId
     * 
     * @return userId
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * 设置userId
     * 
     * @param userId
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 获取登录类型(手机/邮箱/QQ/微信...)
     * 
     * @return 登录类型(手机/邮箱/QQ/微信
     */
    public IdentityType getIdentityType() {
        return this.identityType;
    }

    /**
     * 设置登录类型(手机/邮箱/QQ/微信...)
     * 
     * @param identityType
     *          登录类型(手机/邮箱/QQ/微信
     */
    public void setIdentityType(IdentityType identityType) {
        this.identityType = identityType;
    }

    /**
     * 获取登录唯一标识
     * 
     * @return 登录唯一标识
     */
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * 设置登录唯一标识
     * 
     * @param identifier
     *          登录唯一标识
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * 获取登录凭证
     * 
     * @return 登录凭证
     */
    public String getCredentials() {
        return this.credentials;
    }

    /**
     * 设置登录凭证
     * 
     * @param credentials
     *          登录凭证
     */
    public void setCredentials(String credentials) {
        this.credentials = credentials;
    }

    /**
     * 获取最后登录IP
     * 
     * @return 最后登录IP
     */
    public String getLoginIp() {
        return this.loginIp;
    }

    /**
     * 设置最后登录IP
     * 
     * @param loginIp
     *          最后登录IP
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * 获取最后登录时间
     * 
     * @return 最后登录时间
     */
    public Date getLoginTime() {
        return this.loginTime;
    }

    /**
     * 设置最后登录时间
     * 
     * @param loginTime
     *          最后登录时间
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * 获取createdBy
     * 
     * @return createdBy
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * 设置createdBy
     * 
     * @param createdBy
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * 获取createdTime
     * 
     * @return createdTime
     */
    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    /**
     * 设置createdTime
     * 
     * @param createdTime
     */
    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 获取modifiedBy
     * 
     * @return modifiedBy
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * 设置modifiedBy
     * 
     * @param modifiedBy
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * 获取modifiedTime
     * 
     * @return modifiedTime
     */
    public Timestamp getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * 设置modifiedTime
     * 
     * @param modifiedTime
     */
    public void setModifiedTime(Timestamp modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
    
    @Override
    public boolean sameValueAs(UserAuth other) {
        return this.equals(other);
    }
}