package com.grana.user.domain.model.log;

import java.sql.Timestamp;
import java.util.Date;

/**
 * 数据模型
 * 表：user_login_log
 *
 * @author Aaron Ma
 * @Date 2021-3-1 15:26:29
 */
public class UserLoginLog implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5478157040098119066L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Long id;

    /** 用户id */
    private Long userId;

    /** 用户昵称 */
    private String nickName;

    /** 登录凭证ID */
    private Long authId;

    /** 登录类型(手机/邮箱/QQ/微信...) */
    private String identityType;

    /** 登录唯一标识 */
    private String identifier;

    /** 平台 */
    private String platform;

    /** 登录IP */
    private String loginIp;

    /** 登录时间 */
    private Date loginTime;

    /** createdBy */
    private String createdBy;

    /** createdTime */
    private Timestamp createdTime;

    /** modifiedBy */
    private String modifiedBy;

    /** modifiedTime */
    private Timestamp modifiedTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取用户id
     * 
     * @return 用户id
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * 设置用户id
     * 
     * @param userId
     *          用户id
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 获取用户昵称
     * 
     * @return 用户昵称
     */
    public String getNickName() {
        return this.nickName;
    }

    /**
     * 设置用户昵称
     * 
     * @param nickName
     *          用户昵称
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * 获取登录凭证ID
     * 
     * @return 登录凭证ID
     */
    public Long getAuthId() {
        return this.authId;
    }

    /**
     * 设置登录凭证ID
     * 
     * @param authId
     *          登录凭证ID
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }

    /**
     * 获取登录类型(手机/邮箱/QQ/微信...)
     * 
     * @return 登录类型(手机/邮箱/QQ/微信
     */
    public String getIdentityType() {
        return this.identityType;
    }

    /**
     * 设置登录类型(手机/邮箱/QQ/微信...)
     * 
     * @param identityType
     *          登录类型(手机/邮箱/QQ/微信
     */
    public void setIdentityType(String identityType) {
        this.identityType = identityType;
    }

    /**
     * 获取登录唯一标识
     * 
     * @return 登录唯一标识
     */
    public String getIdentifier() {
        return this.identifier;
    }

    /**
     * 设置登录唯一标识
     * 
     * @param identifier
     *          登录唯一标识
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * 获取平台
     * 
     * @return 平台
     */
    public String getPlatform() {
        return this.platform;
    }

    /**
     * 设置平台
     * 
     * @param platform
     *          平台
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * 获取登录IP
     * 
     * @return 登录IP
     */
    public String getLoginIp() {
        return this.loginIp;
    }

    /**
     * 设置登录IP
     * 
     * @param loginIp
     *          登录IP
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * 获取登录时间
     * 
     * @return 登录时间
     */
    public Date getLoginTime() {
        return this.loginTime;
    }

    /**
     * 设置登录时间
     * 
     * @param loginTime
     *          登录时间
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * 获取createdBy
     * 
     * @return createdBy
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * 设置createdBy
     * 
     * @param createdBy
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * 获取createdTime
     * 
     * @return createdTime
     */
    public Timestamp getCreatedTime() {
        return this.createdTime;
    }

    /**
     * 设置createdTime
     * 
     * @param createdTime
     */
    public void setCreatedTime(Timestamp createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 获取modifiedBy
     * 
     * @return modifiedBy
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * 设置modifiedBy
     * 
     * @param modifiedBy
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * 获取modifiedTime
     * 
     * @return modifiedTime
     */
    public Timestamp getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * 设置modifiedTime
     * 
     * @param modifiedTime
     */
    public void setModifiedTime(Timestamp modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}